packages:
  - apps/*
  - libs/*
  - tools/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - less
  - nx
  - prisma
  - unrs-resolver
