-- CreateEnum
CREATE TYPE "FilterType" AS ENUM ('TEXT', 'NUMBER', 'DATE', 'SELECT', 'MULTI_SELECT', 'BOOLEAN', 'RELATION');

-- DropIndex
DROP INDEX "idx_case_address_911_trgm";

-- DropIndex
DROP INDEX "idx_case_city_trgm";

-- DropIndex
DROP INDEX "idx_case_incident_type_trgm";

-- DropIndex
DROP INDEX "idx_case_state_trgm";

-- DropIndex
DROP INDEX "idx_case_zip_trgm";

-- CreateTable
CREATE TABLE "Filter" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "field" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "type" "FilterType" NOT NULL,
    "operators" JSONB,
    "dependencies" JSONB,
    "isMulti" BOOLEAN NOT NULL DEFAULT false,
    "isRequired" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "dataSource" TEXT,
    "placeholder" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Filter_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Filter_field_key" ON "Filter"("field");
