-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "citext";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- CreateEnum
CREATE TYPE "user_status" AS ENUM ('PENDING', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'REJECTED', 'INVITED', 'REVOKED');

-- CreateEnum
CREATE TYPE "notification_type" AS ENUM ('SYSTEM', 'ACCOUNT', 'INVITE', 'APPROVAL');

-- CreateEnum
CREATE TYPE "notification_severity" AS ENUM ('INFO', 'WARNING', 'URGENT');

-- CreateEnum
CREATE TYPE "invite_status" AS ENUM ('PENDING', 'ACCEPTED', 'REVOKED');

-- CreateEnum
CREATE TYPE "permission_scope" AS ENUM ('ALL', 'OWN', 'ASSIGNED', 'TEAM');

-- CreateEnum
CREATE TYPE "user_type" AS ENUM ('USER', 'AGENCY', 'ATTORNEY');

-- CreateTable
CREATE TABLE "roles" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" CITEXT NOT NULL,
    "description" VARCHAR(500),
    "is_built_in" BOOLEAN NOT NULL DEFAULT false,
    "level" INTEGER NOT NULL DEFAULT 0,
    "is_external" BOOLEAN NOT NULL DEFAULT false,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "deleted_at" TIMESTAMPTZ,
    "deleted_by" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "permissions" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "module" VARCHAR(100) NOT NULL,
    "action" VARCHAR(100) NOT NULL,
    "description" VARCHAR(500),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "role_permissions" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role_id" INTEGER NOT NULL,
    "permission_id" INTEGER NOT NULL,
    "scope" "permission_scope" NOT NULL DEFAULT 'ALL',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_roles" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "role_id" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" INTEGER,

    CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_invitations" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "invited_by" INTEGER,
    "token_hash" TEXT,
    "token_expiry" TIMESTAMPTZ,
    "status" "invite_status" NOT NULL DEFAULT 'PENDING',
    "accepted_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "user_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "refresh_token_hash" VARCHAR(255) NOT NULL,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "metadata" JSONB,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER,
    "action" VARCHAR(100) NOT NULL,
    "entity_type" VARCHAR(100) NOT NULL,
    "entity_id" VARCHAR(100),
    "changes" JSONB,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "correlation_id" VARCHAR(100),
    "severity" VARCHAR(20),
    "description" VARCHAR(500),
    "resource_name" VARCHAR(200),
    "http_method" VARCHAR(10),
    "http_path" VARCHAR(500),
    "status_code" INTEGER,
    "duration" INTEGER,
    "target_user_id" INTEGER,
    "outcome" VARCHAR(20),
    "session_id" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" VARCHAR(100),
    "last_name" VARCHAR(100),
    "email" VARCHAR(255) NOT NULL,
    "phone" VARCHAR(20),
    "password_hash" VARCHAR(255),
    "previous_password_hash" VARCHAR(255),
    "type" "user_type" NOT NULL DEFAULT 'USER',
    "city" VARCHAR(100),
    "state" VARCHAR(50),
    "zip" VARCHAR(20),
    "is_credential_enabled" BOOLEAN NOT NULL DEFAULT true,
    "status" "user_status" NOT NULL DEFAULT 'PENDING',
    "reset_token" VARCHAR(255),
    "password_reset_requested_at" TIMESTAMPTZ,
    "login_attempts" INTEGER NOT NULL DEFAULT 0,
    "login_attempts_lockout" TIMESTAMPTZ,
    "last_login_at" TIMESTAMPTZ,
    "reviewed_by" INTEGER,
    "reviewed_at" TIMESTAMPTZ,
    "rejection_reason" TEXT,
    "suspended_at" TIMESTAMPTZ,
    "suspended_by" INTEGER,
    "deactivated_at" TIMESTAMPTZ,
    "deactivated_by" INTEGER,
    "set_password_token" VARCHAR(255),
    "set_password_requested_at" TIMESTAMPTZ,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "deleted_at" TIMESTAMPTZ,
    "deleted_by" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "two_factor_grace_period_end" TIMESTAMPTZ,
    "is_two_factor_enabled" BOOLEAN NOT NULL DEFAULT false,
    "is_two_factor_enforced" BOOLEAN NOT NULL DEFAULT false,
    "two_factor_secret" VARCHAR(500),
    "two_factor_confirmed_at" TIMESTAMPTZ,
    "two_factor_attempts" INTEGER NOT NULL DEFAULT 0,
    "two_factor_attempts_lockout" TIMESTAMPTZ,
    "two_factor_recovery_token" VARCHAR(255),
    "two_factor_recovery_requested_at" TIMESTAMPTZ,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_settings" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "in_app_enabled" BOOLEAN NOT NULL DEFAULT true,
    "email_enabled" BOOLEAN NOT NULL DEFAULT true,
    "sms_enabled" BOOLEAN NOT NULL DEFAULT false,
    "push_enabled" BOOLEAN NOT NULL DEFAULT false,
    "promotional_enabled" BOOLEAN NOT NULL DEFAULT true,
    "quiet_hours_start" VARCHAR(5),
    "quiet_hours_end" VARCHAR(5),
    "notification_overrides" JSONB,
    "timezone" VARCHAR(50) NOT NULL DEFAULT 'UTC',
    "reminder_hour_local" INTEGER NOT NULL DEFAULT 10,
    "locale" VARCHAR(10) NOT NULL DEFAULT 'en-US',
    "theme" VARCHAR(10) NOT NULL DEFAULT 'SYSTEM',
    "default_landing_page" VARCHAR(100) NOT NULL DEFAULT '/dashboard',
    "sidebar_collapsed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "user_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "backup_codes" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "hash" VARCHAR(255) NOT NULL,
    "used_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "backup_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "trusted_devices" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "token_hash" VARCHAR(255) NOT NULL,
    "label" VARCHAR(255),
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "trusted_devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_change_logs" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "source" VARCHAR(50) NOT NULL,
    "from_state" JSONB NOT NULL,
    "to_state" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "provider_change_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "recipient_id" INTEGER NOT NULL,
    "type" "notification_type" NOT NULL,
    "severity" "notification_severity" NOT NULL DEFAULT 'INFO',
    "main_title" TEXT,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "metadata" JSONB,
    "entity_type" VARCHAR(50),
    "entity_id" INTEGER,
    "is_read" BOOLEAN NOT NULL DEFAULT false,
    "read_at" TIMESTAMPTZ,
    "job_id" TEXT,
    "category" VARCHAR(50),
    "event_key" VARCHAR(100),
    "group_key" VARCHAR(255),
    "expires_at" TIMESTAMPTZ,
    "scheduled_for_utc" TIMESTAMPTZ,
    "scheduled_timezone" VARCHAR(50),
    "original_local_time" VARCHAR(10),
    "snoozed_until" TIMESTAMPTZ,
    "actor_id" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_deliveries" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "notification_id" INTEGER NOT NULL,
    "channel" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    "delivered_at" TIMESTAMPTZ,
    "failed_at" TIMESTAMPTZ,
    "failure_reason" TEXT,
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "notification_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "seed_registry" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "applied_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "seed_registry_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "roles_name_key" ON "roles"("name");

-- CreateIndex
CREATE UNIQUE INDEX "uq_permission_module_action" ON "permissions"("module", "action");

-- CreateIndex
CREATE INDEX "idx_role_permission_role" ON "role_permissions"("role_id");

-- CreateIndex
CREATE INDEX "idx_role_permission_perm" ON "role_permissions"("permission_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_role_permission_scope" ON "role_permissions"("role_id", "permission_id", "scope");

-- CreateIndex
CREATE INDEX "idx_user_role_user" ON "user_roles"("user_id");

-- CreateIndex
CREATE INDEX "idx_user_role_role" ON "user_roles"("role_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_user_role" ON "user_roles"("user_id", "role_id");

-- CreateIndex
CREATE UNIQUE INDEX "user_invitations_user_id_key" ON "user_invitations"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "user_invitations_token_hash_key" ON "user_invitations"("token_hash");

-- CreateIndex
CREATE INDEX "idx_invitation_invited_by" ON "user_invitations"("invited_by");

-- CreateIndex
CREATE INDEX "idx_invitation_status" ON "user_invitations"("status");

-- CreateIndex
CREATE INDEX "idx_session_user" ON "sessions"("user_id");

-- CreateIndex
CREATE INDEX "idx_session_expires_at" ON "sessions"("expires_at");

-- CreateIndex
CREATE INDEX "idx_audit_entity" ON "audit_logs"("entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "idx_audit_user" ON "audit_logs"("user_id");

-- CreateIndex
CREATE INDEX "idx_audit_created_at" ON "audit_logs"("created_at");

-- CreateIndex
CREATE INDEX "idx_audit_severity" ON "audit_logs"("severity");

-- CreateIndex
CREATE INDEX "idx_audit_target_user" ON "audit_logs"("target_user_id");

-- CreateIndex
CREATE INDEX "idx_audit_action_target_created" ON "audit_logs"("action", "target_user_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_two_factor_recovery_token_key" ON "users"("two_factor_recovery_token");

-- CreateIndex
CREATE INDEX "idx_user_status" ON "users"("status");

-- CreateIndex
CREATE INDEX "idx_user_reset_token" ON "users"("reset_token");

-- CreateIndex
CREATE INDEX "idx_user_deleted_by" ON "users"("deleted_by");

-- CreateIndex
CREATE INDEX "idx_user_reviewed_by" ON "users"("reviewed_by");

-- CreateIndex
CREATE INDEX "idx_user_suspended_by" ON "users"("suspended_by");

-- CreateIndex
CREATE INDEX "idx_user_deactivated_by" ON "users"("deactivated_by");

-- CreateIndex
CREATE INDEX "idx_user_set_password_token" ON "users"("set_password_token");

-- CreateIndex
CREATE INDEX "idx_user_2fa_enforcement" ON "users"("is_two_factor_enforced", "two_factor_grace_period_end");

-- CreateIndex
CREATE INDEX "idx_user_created_at" ON "users"("created_at");

-- CreateIndex
CREATE INDEX "idx_user_last_login_at" ON "users"("last_login_at");

-- CreateIndex
CREATE INDEX "idx_user_first_name_trgm" ON "users" USING GIN ("first_name" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "idx_user_last_name_trgm" ON "users" USING GIN ("last_name" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "idx_user_email_trgm" ON "users" USING GIN ("email" gin_trgm_ops);

-- CreateIndex
CREATE UNIQUE INDEX "user_settings_user_id_key" ON "user_settings"("user_id");

-- CreateIndex
CREATE INDEX "idx_backup_code_user" ON "backup_codes"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "trusted_devices_token_hash_key" ON "trusted_devices"("token_hash");

-- CreateIndex
CREATE INDEX "idx_trusted_device_user" ON "trusted_devices"("user_id");

-- CreateIndex
CREATE INDEX "idx_trusted_device_expires" ON "trusted_devices"("expires_at");

-- CreateIndex
CREATE INDEX "idx_pcl_user_created" ON "provider_change_logs"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "idx_pcl_source_created" ON "provider_change_logs"("source", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "notifications_job_id_key" ON "notifications"("job_id");

-- CreateIndex
CREATE INDEX "idx_notification_recipient" ON "notifications"("recipient_id");

-- CreateIndex
CREATE INDEX "idx_notification_recipient_read" ON "notifications"("recipient_id", "is_read");

-- CreateIndex
CREATE INDEX "idx_notification_created_at" ON "notifications"("created_at");

-- CreateIndex
CREATE INDEX "idx_notification_category" ON "notifications"("category");

-- CreateIndex
CREATE INDEX "idx_notification_scheduled" ON "notifications"("scheduled_for_utc");

-- CreateIndex
CREATE INDEX "idx_notification_snoozed" ON "notifications"("snoozed_until");

-- CreateIndex
CREATE INDEX "idx_notification_expires" ON "notifications"("expires_at");

-- CreateIndex
CREATE INDEX "idx_notification_actor" ON "notifications"("actor_id");

-- CreateIndex
CREATE INDEX "idx_notification_recipient_feed" ON "notifications"("recipient_id", "created_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "idx_notification_entity" ON "notifications"("entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "idx_delivery_status" ON "notification_deliveries"("status");

-- CreateIndex
CREATE INDEX "idx_delivery_channel_status" ON "notification_deliveries"("channel", "status");

-- CreateIndex
CREATE UNIQUE INDEX "uq_delivery_notification_channel" ON "notification_deliveries"("notification_id", "channel");

-- CreateIndex
CREATE UNIQUE INDEX "seed_registry_name_key" ON "seed_registry"("name");

-- AddForeignKey
ALTER TABLE "roles" ADD CONSTRAINT "roles_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_invitations" ADD CONSTRAINT "user_invitations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_invitations" ADD CONSTRAINT "user_invitations_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_suspended_by_fkey" FOREIGN KEY ("suspended_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_deactivated_by_fkey" FOREIGN KEY ("deactivated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "backup_codes" ADD CONSTRAINT "backup_codes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trusted_devices" ADD CONSTRAINT "trusted_devices_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_change_logs" ADD CONSTRAINT "provider_change_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_deliveries" ADD CONSTRAINT "notification_deliveries_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
