import { BuiltInRole, ModuleName as M, PermissionAction as A } from '@mediastar/core';

import { type PermissionScope, PermissionScope as S } from '../../generated/prisma/client';

interface RolePermissionSeed {
  module: string;
  action: string;
  scope: PermissionScope;
}

interface RoleSeed {
  name: string;
  description: string;
  level: number;
  permissions: readonly RolePermissionSeed[];
  isBuiltIn: boolean;
}

const ALL = S.ALL;
const OWN = S.OWN;
const ASSIGNED = S.ASSIGNED;
const TEAM = S.TEAM;

export const BUILT_IN_ROLES: ReadonlyArray<RoleSeed> = [
  {
    name: BuiltInRole.Owner,
    description: 'Full system access with wildcard permissions',
    level: 100,
    isBuiltIn: true,
    permissions: [{ module: '*', action: '*', scope: ALL }],
  },
  {
    name: BuiltInRole.Admin,
    description: 'Administrative access to most modules',
    level: 90,
    isBuiltIn: true,
    permissions: [
      { module: M.Users, action: A.Create, scope: ALL },
      { module: M.Users, action: A.Read, scope: ALL },
      { module: M.Users, action: A.Update, scope: ALL },
      { module: M.Users, action: A.Delete, scope: ALL },
      { module: M.Users, action: A.Admin, scope: ALL },
      { module: M.Roles, action: A.Read, scope: ALL },
      { module: M.Roles, action: A.Create, scope: ALL },
      { module: M.Roles, action: A.Update, scope: ALL },
      { module: M.Roles, action: A.Delete, scope: ALL },
      { module: M.Roles, action: A.Admin, scope: ALL },
      { module: M.Cases, action: A.Create, scope: ALL },
      { module: M.Cases, action: A.Read, scope: ALL },
      { module: M.Cases, action: A.Update, scope: ALL },
      { module: M.Cases, action: A.Delete, scope: ALL },
      { module: M.Cases, action: A.Export, scope: ALL },
      { module: M.Agencies, action: A.Create, scope: ALL },
      { module: M.Agencies, action: A.Read, scope: ALL },
      { module: M.Agencies, action: A.Update, scope: ALL },
      { module: M.Agencies, action: A.Delete, scope: ALL },
      { module: M.Agencies, action: A.Export, scope: ALL },
      { module: M.Emails, action: A.Create, scope: ALL },
      { module: M.Emails, action: A.Read, scope: ALL },
      { module: M.Emails, action: A.Update, scope: ALL },
      { module: M.Emails, action: A.Delete, scope: ALL },
      { module: M.Templates, action: A.Admin, scope: ALL },
      { module: M.Reports, action: A.Read, scope: ALL },
      { module: M.Reports, action: A.Export, scope: ALL },
      { module: M.Attorneys, action: A.Create, scope: ALL },
      { module: M.Attorneys, action: A.Read, scope: ALL },
      { module: M.Attorneys, action: A.Update, scope: ALL },
      { module: M.Attorneys, action: A.Delete, scope: ALL },
      { module: M.Files, action: A.Create, scope: ALL },
      { module: M.Files, action: A.Read, scope: ALL },
      { module: M.Files, action: A.Delete, scope: ALL },
      { module: M.Audit, action: A.Read, scope: ALL },
      { module: M.Settings, action: A.Read, scope: ALL },
      { module: M.Settings, action: A.Update, scope: ALL },
      { module: M.Settings, action: A.Admin, scope: ALL },
      { module: M.Auth, action: A.Read, scope: ALL },
      { module: M.Auth, action: A.Admin, scope: ALL },
      { module: M.Tasks, action: A.Create, scope: ALL },
      { module: M.Tasks, action: A.Read, scope: ALL },
      { module: M.Tasks, action: A.Update, scope: ALL },
      { module: M.Tasks, action: A.Delete, scope: ALL },
      { module: M.Reminders, action: A.Create, scope: ALL },
      { module: M.Reminders, action: A.Read, scope: ALL },
      { module: M.Reminders, action: A.Update, scope: ALL },
      { module: M.Reminders, action: A.Delete, scope: ALL },
      { module: M.Teams, action: A.Read, scope: ALL },
      { module: M.Teams, action: A.Admin, scope: ALL },
      { module: M.AgencyRequests, action: A.Create, scope: ALL },
      { module: M.AgencyRequests, action: A.Read, scope: ALL },
      { module: M.AgencyRequests, action: A.Update, scope: ALL },
      { module: M.AgencyRequests, action: A.Delete, scope: ALL },
      { module: M.AgencyRequests, action: A.Manage, scope: ALL },
      { module: M.Trash, action: A.View, scope: ALL },
      { module: M.Trash, action: A.Restore, scope: ALL },
      { module: M.Trash, action: A.HardDelete, scope: ALL },
      { module: M.Leaderboard, action: A.Read, scope: ALL },
      { module: M.Leaderboard, action: A.Manage, scope: ALL },
    ],
  },
  {
    name: BuiltInRole.Employee,
    description: 'Operational case management access',
    level: 80,
    isBuiltIn: true,
    permissions: [
      { module: M.Cases, action: A.Create, scope: ALL },
      { module: M.Cases, action: A.Read, scope: ALL },
      { module: M.Cases, action: A.Update, scope: OWN },
      { module: M.Cases, action: A.Export, scope: OWN },
      { module: M.Agencies, action: A.Create, scope: ALL },
      { module: M.Agencies, action: A.Read, scope: ALL },
      { module: M.Agencies, action: A.Update, scope: ALL },
      { module: M.Emails, action: A.Read, scope: OWN },
      { module: M.Emails, action: A.Create, scope: OWN },
      { module: M.Attorneys, action: A.Read, scope: ALL },
      { module: M.Files, action: A.Create, scope: ALL },
      { module: M.Files, action: A.Read, scope: ALL },
      { module: M.Reports, action: A.Read, scope: OWN },
      { module: M.Tasks, action: A.Create, scope: ALL },
      { module: M.Tasks, action: A.Read, scope: ALL },
      { module: M.Tasks, action: A.Update, scope: ASSIGNED },
      { module: M.Tasks, action: A.Delete, scope: OWN },
      { module: M.Reminders, action: A.Create, scope: ALL },
      { module: M.Reminders, action: A.Read, scope: ALL },
      { module: M.Reminders, action: A.Update, scope: ASSIGNED },
      { module: M.Reminders, action: A.Delete, scope: OWN },
      { module: M.AgencyRequests, action: A.Create, scope: ALL },
      { module: M.AgencyRequests, action: A.Read, scope: ALL },
      { module: M.AgencyRequests, action: A.Update, scope: ALL },
      { module: M.AgencyRequests, action: A.Delete, scope: OWN },
      { module: M.Cases, action: A.Manage, scope: TEAM },
      // Trash UI access matches prior delete-scope semantics — bulk action
      // safety relies on per-service ownership filtering of `dto.ids`.
      { module: M.Trash, action: A.View, scope: OWN },
      { module: M.Trash, action: A.Restore, scope: OWN },
      { module: M.Trash, action: A.HardDelete, scope: OWN },
      { module: M.Leaderboard, action: A.Read, scope: ALL },
    ],
  },
  {
    name: BuiltInRole.Contractor,
    description: 'Same as employee without attorney visibility',
    level: 70,
    isBuiltIn: true,
    permissions: [
      { module: M.Cases, action: A.Create, scope: ALL },
      { module: M.Cases, action: A.Read, scope: ALL },
      { module: M.Cases, action: A.Update, scope: OWN },
      { module: M.Cases, action: A.Export, scope: OWN },
      { module: M.Agencies, action: A.Create, scope: ALL },
      { module: M.Agencies, action: A.Read, scope: ALL },
      { module: M.Agencies, action: A.Update, scope: ALL },
      { module: M.Emails, action: A.Read, scope: OWN },
      { module: M.Emails, action: A.Create, scope: OWN },
      { module: M.Files, action: A.Create, scope: ALL },
      { module: M.Files, action: A.Read, scope: ALL },
      { module: M.Reports, action: A.Read, scope: OWN },
      { module: M.Tasks, action: A.Create, scope: ALL },
      { module: M.Tasks, action: A.Read, scope: ALL },
      { module: M.Tasks, action: A.Update, scope: ASSIGNED },
      { module: M.Tasks, action: A.Delete, scope: OWN },
      { module: M.Reminders, action: A.Create, scope: ALL },
      { module: M.Reminders, action: A.Read, scope: ALL },
      { module: M.AgencyRequests, action: A.Create, scope: ALL },
      { module: M.AgencyRequests, action: A.Read, scope: ALL },
      { module: M.AgencyRequests, action: A.Update, scope: ALL },
      { module: M.AgencyRequests, action: A.Delete, scope: OWN },
      { module: M.Cases, action: A.Manage, scope: TEAM },
      { module: M.Trash, action: A.View, scope: OWN },
      { module: M.Trash, action: A.Restore, scope: OWN },
      { module: M.Trash, action: A.HardDelete, scope: OWN },
      { module: M.Leaderboard, action: A.Read, scope: ALL },
    ],
  },
  {
    name: BuiltInRole.Attorney,
    description: 'Assigned cases only',
    level: 60,
    isBuiltIn: true,
    permissions: [
      { module: M.Cases, action: A.Read, scope: ASSIGNED },
      { module: M.Files, action: A.Create, scope: ASSIGNED },
      { module: M.Files, action: A.Read, scope: ASSIGNED },
      { module: M.Tasks, action: A.Read, scope: ASSIGNED },
      { module: M.Tasks, action: A.Update, scope: ASSIGNED },
      { module: M.Reminders, action: A.Read, scope: ASSIGNED },
      { module: M.AgencyRequests, action: A.Read, scope: ASSIGNED },
      { module: M.Cases, action: A.Read, scope: TEAM },
    ],
  },
  {
    name: BuiltInRole.User,
    description: 'Minimal read-only access',
    level: 50,
    isBuiltIn: true,
    permissions: [
      { module: M.Cases, action: A.Read, scope: OWN },
      { module: M.Reminders, action: A.Read, scope: OWN },
    ],
  },
];
