export enum ErrorCode {
  // Generic (existing)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  JSON_PARSE_ERROR = 'JSON_PARSE_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  DATABASE_ERROR = 'DATABASE_ERROR',
  HTTP_ERROR = 'HTTP_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Case domain
  CASE_NOT_FOUND = 'CASE_NOT_FOUND',
  CASE_DRAFT_INVALID = 'CASE_DRAFT_INVALID',
  CASE_TRANSITION_BLOCKED = 'CASE_TRANSITION_BLOCKED',
  CASE_ASSIGNEE_ALREADY_LINKED = 'CASE_ASSIGNEE_ALREADY_LINKED',
  CASE_ASSIGNEE_NOT_LINKED = 'CASE_ASSIGNEE_NOT_LINKED',
  CASE_AGENCY_ALREADY_LINKED = 'CASE_AGENCY_ALREADY_LINKED',
  CASE_AGENCY_NOT_LINKED = 'CASE_AGENCY_NOT_LINKED',

  // User domain
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_INVITATION_EXPIRED = 'USER_INVITATION_EXPIRED',

  // Auth domain
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_2FA_REQUIRED = 'AUTH_2FA_REQUIRED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // Role domain
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_HIERARCHY_VIOLATION = 'ROLE_HIERARCHY_VIOLATION',

  // Pipeline domain
  PIPELINE_STATUS_NOT_FOUND = 'PIPELINE_STATUS_NOT_FOUND',

  // General
  ENTITY_IDS_INVALID = 'ENTITY_IDS_INVALID',
  RATE_LIMITED = 'RATE_LIMITED',
}
