export enum ModuleName {
  Users = 'users',
  Roles = 'roles',
  Cases = 'cases',
  Files = 'files',
  Leaderboard = 'leaderboard',
  Emails = 'emails',
  Billing = 'billing',
  Settings = 'settings',
  Agencies = 'agencies',
  AgencyRequests = 'agency_requests',
  Templates = 'templates',
  Reports = 'reports',
  Attorneys = 'attorneys',
  Audit = 'audit',
  PipelineStatuses = 'pipeline_statuses',
  Stages = 'stages',
  TransitionRules = 'transition_rules',
  Themes = 'themes',
  Auth = 'auth',
  Notifications = 'notifications',
  Reminders = 'reminders',
  Tasks = 'tasks',
  Teams = 'teams',
  Trash = 'trash',
}
