/**
 * Post-processing script for Prisma migrations.
 *
 * Prisma generates SERIAL / BIGSERIAL for @default(autoincrement()) columns.
 * This script converts them to the modern SQL-standard IDENTITY syntax:
 *   SERIAL NOT NULL      → INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
 *   BIGSERIAL NOT NULL   → BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
 *
 * Usage:
 *   tsx libs/database/prisma/scripts/fix-serial-to-identity.ts [--all]
 *
 *   Without flags  → processes only the most recent migration directory
 *   --all          → processes every migration directory
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const MIGRATIONS_DIR = resolve(__dirname, '..', 'migrations');

function log(message: string): void {
  process.stdout.write(`${message}\n`);
}

const REPLACEMENTS: ReadonlyArray<readonly [RegExp, string]> = [
  [/SERIAL NOT NULL/g, 'INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY'],
  [/BIGSERIAL NOT NULL/g, 'BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY'],
];

function processMigration(dirPath: string): boolean {
  const sqlPath = join(dirPath, 'migration.sql');
  let sql: string;

  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- sqlPath built from constant MIGRATIONS_DIR + directory name
    sql = readFileSync(sqlPath, 'utf-8');
  } catch {
    return false;
  }

  let changed = false;
  let result = sql;

  for (const [pattern, replacement] of REPLACEMENTS) {
    const next = result.replace(pattern, replacement);
    if (next !== result) {
      changed = true;
      result = next;
    }
  }

  if (changed) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- sqlPath built from constant MIGRATIONS_DIR + directory name
    writeFileSync(sqlPath, result, 'utf-8');
  }

  return changed;
}

function getMigrationDirs(): readonly string[] {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- MIGRATIONS_DIR is a resolved constant, not user input
  return readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

function main(): void {
  const processAll = process.argv.includes('--all');
  const dirs = getMigrationDirs();

  if (dirs.length === 0) {
    log('No migration directories found.');
    return;
  }

  const lastDir = dirs[dirs.length - 1];
  let targets: readonly string[];
  if (processAll) {
    targets = dirs;
  } else {
    targets = lastDir ? [lastDir] : [];
  }

  let totalFixed = 0;

  for (const dir of targets) {
    const dirPath = join(MIGRATIONS_DIR, dir);
    const fixed = processMigration(dirPath);
    if (fixed) {
      log(`Fixed: ${dir}/migration.sql`);
      totalFixed++;
    }
  }

  if (totalFixed === 0) {
    log('No SERIAL/BIGSERIAL occurrences found — nothing to fix.');
  } else {
    log(`Done. Fixed ${totalFixed} migration(s).`);
  }
}

main();
