-- AlterTable
ALTER TABLE "Case" ADD COLUMN     "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
